require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ContactexpertsController do

  # This should return the minimal set of attributes required to create a valid
  # Contactexpert. As you add validations to Contactexpert, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContactexpertsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contactexperts as @contactexperts" do
      contactexpert = Contactexpert.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contactexperts).should eq([contactexpert])
    end
  end

  describe "GET show" do
    it "assigns the requested contactexpert as @contactexpert" do
      contactexpert = Contactexpert.create! valid_attributes
      get :show, {:id => contactexpert.to_param}, valid_session
      assigns(:contactexpert).should eq(contactexpert)
    end
  end

  describe "GET new" do
    it "assigns a new contactexpert as @contactexpert" do
      get :new, {}, valid_session
      assigns(:contactexpert).should be_a_new(Contactexpert)
    end
  end

  describe "GET edit" do
    it "assigns the requested contactexpert as @contactexpert" do
      contactexpert = Contactexpert.create! valid_attributes
      get :edit, {:id => contactexpert.to_param}, valid_session
      assigns(:contactexpert).should eq(contactexpert)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contactexpert" do
        expect {
          post :create, {:contactexpert => valid_attributes}, valid_session
        }.to change(Contactexpert, :count).by(1)
      end

      it "assigns a newly created contactexpert as @contactexpert" do
        post :create, {:contactexpert => valid_attributes}, valid_session
        assigns(:contactexpert).should be_a(Contactexpert)
        assigns(:contactexpert).should be_persisted
      end

      it "redirects to the created contactexpert" do
        post :create, {:contactexpert => valid_attributes}, valid_session
        response.should redirect_to(Contactexpert.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contactexpert as @contactexpert" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contactexpert.any_instance.stub(:save).and_return(false)
        post :create, {:contactexpert => {}}, valid_session
        assigns(:contactexpert).should be_a_new(Contactexpert)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contactexpert.any_instance.stub(:save).and_return(false)
        post :create, {:contactexpert => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contactexpert" do
        contactexpert = Contactexpert.create! valid_attributes
        # Assuming there are no other contactexperts in the database, this
        # specifies that the Contactexpert created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contactexpert.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => contactexpert.to_param, :contactexpert => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested contactexpert as @contactexpert" do
        contactexpert = Contactexpert.create! valid_attributes
        put :update, {:id => contactexpert.to_param, :contactexpert => valid_attributes}, valid_session
        assigns(:contactexpert).should eq(contactexpert)
      end

      it "redirects to the contactexpert" do
        contactexpert = Contactexpert.create! valid_attributes
        put :update, {:id => contactexpert.to_param, :contactexpert => valid_attributes}, valid_session
        response.should redirect_to(contactexpert)
      end
    end

    describe "with invalid params" do
      it "assigns the contactexpert as @contactexpert" do
        contactexpert = Contactexpert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contactexpert.any_instance.stub(:save).and_return(false)
        put :update, {:id => contactexpert.to_param, :contactexpert => {}}, valid_session
        assigns(:contactexpert).should eq(contactexpert)
      end

      it "re-renders the 'edit' template" do
        contactexpert = Contactexpert.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contactexpert.any_instance.stub(:save).and_return(false)
        put :update, {:id => contactexpert.to_param, :contactexpert => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contactexpert" do
      contactexpert = Contactexpert.create! valid_attributes
      expect {
        delete :destroy, {:id => contactexpert.to_param}, valid_session
      }.to change(Contactexpert, :count).by(-1)
    end

    it "redirects to the contactexperts list" do
      contactexpert = Contactexpert.create! valid_attributes
      delete :destroy, {:id => contactexpert.to_param}, valid_session
      response.should redirect_to(contactexperts_url)
    end
  end

end
